### ISSUE TITLE
What is this code used for?

### ISSUE THREAD

**Issue by xaque208** [dustin/go-aprs#6]
I'm currently exploring go projects for packet radio.  What are you doing here?  What are you interfacing with?

**Comment by dustin** [comment]
It's for anything that wants to work with APRS.  I used to have a gateway running talking to a local xastir to get a stream and process it.  I've mostly moved to my [other APRS project](/dustin/haprs) for that sort of thing since I found it a bit easier to hit most of the edge cases in haskell.  Of course, the spec has a bit of ambiguity to it that makes it impossible to get right altogether.

I know someone was using this for some projects a few years back, but I've not kept up with the progress.

**Comment by xaque208** [comment]
Are you interfacing with hardware at all, or KISS or what protocols are involved here?  Or fetching data from apris.fi?  I'll check out your other project too.  Not that I can help much with haskell, but I'm wanting to do a bit of packet radio.

**Comment by dustin** [comment]
Well, I think I theoretically could do anything above actual signal processing, so as long as I have something that can give me ax.25 packets, it should be OK.  I run xastir on a raspberry pi with a hardware TNC and relay back and forth.  Then I talk to that with my own software.
 
Haskell is sort of like vi.  It's kind of weird relative to other things, but once you get used to it, it's far easier to get correct things done than most other languages.  For me, anyway.
